/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "server_hora.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
imprimir_1(struct server_estructura arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, IMPRIMIR,
		(xdrproc_t) xdr_server_estructura, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
