/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVER_HORA_H_RPCGEN
#define _SERVER_HORA_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct server_estructura {
	char user[256];
	char op[512];
	char fecha[256];
	char hora[256];
};
typedef struct server_estructura server_estructura;

#define SERVER_HORA 99
#define SERVER_HORA_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define IMPRIMIR 1
extern  enum clnt_stat imprimir_1(struct server_estructura , int *, CLIENT *);
extern  bool_t imprimir_1_svc(struct server_estructura , int *, struct svc_req *);
extern int server_hora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define IMPRIMIR 1
extern  enum clnt_stat imprimir_1();
extern  bool_t imprimir_1_svc();
extern int server_hora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_server_estructura (XDR *, server_estructura*);

#else /* K&R C */
extern bool_t xdr_server_estructura ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVER_HORA_H_RPCGEN */
